# Option Pricing using Binomial Model

In [26]:
#Importing Libraries
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [27]:
#Assumed values
rf = 0.06
S0 = 12089
K = 12200
T = 50/365
nT = 10
delT = T/nT
sig = 0.15

In [28]:
u = np.exp(sig*np.sqrt(delT))
d = 1/u
p = (np.exp(rf*delT)-d)/(u-d)

In [29]:
asset_price = np.zeros((nT,nT))
asset_price

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [37]:
for i in range(0,nT):
    for j in range(0,i+1):
        asset_price[j,i] = S0*(u**(i-j))*(d**(j))
asset_price       

array([[12089.        , 12303.11054567, 12521.01324337, 12742.7752566 ,
        12968.46493842, 13198.15185252, 13431.90679462, 13669.80181432,
        13911.91023733, 14158.30668801],
       [    0.        , 11878.61561167, 12089.        , 12303.11054567,
        12521.01324337, 12742.7752566 , 12968.46493842, 13198.15185252,
        13431.90679462, 13669.80181432],
       [    0.        ,     0.        , 11671.89253453, 11878.61561167,
        12089.        , 12303.11054567, 12521.01324337, 12742.7752566 ,
        12968.46493842, 13198.15185252],
       [    0.        ,     0.        ,     0.        , 11468.76705091,
        11671.89253453, 11878.61561167, 12089.        , 12303.11054567,
        12521.01324337, 12742.7752566 ],
       [    0.        ,     0.        ,     0.        ,     0.        ,
        11269.17655204, 11468.76705091, 11671.89253453, 11878.61561167,
        12089.        , 12303.11054567],
       [    0.        ,     0.        ,     0.        ,     0.        ,
   

In [41]:
intrinsic_val = np.zeros((nT,nT))
intrinsic_val[:,nT-1] = np.maximum(np.zeros(nT),asset_price[:,nT-1]-K)
intrinsic_val

array([[   0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        , 1958.30668801],
       [   0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        , 1469.80181432],
       [   0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,  998.15185252],
       [   0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,  542.7752566 ],
       [   0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,  103.11054567],
       [   0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0

In [43]:
for i in range(nT-1,-1,-1):
    for j in range(0,i):
        intrinsic_val[j,i-1]=(p*intrinsic_val[j,i]+(1-p)*intrinsic_val[j+1,i])*np.exp(-rf*delT)

In [44]:
intrinsic_val[0][0]

246.73985737435623