# Mutual Fund Creation

In [105]:
#Importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [106]:
#Importing the dataset
stocks = pd.read_excel("Stock Data.xlsx", sheet_name="Returns")
stocks.head()

Date  HDFC Bank  Kotak Mahindra Bank  ICICI Bank  Bajaj Finance  \
0 2019-12-31  -0.007066            -0.002192   -0.009560      -0.000649   
1 2019-12-30   0.004667             0.001869   -0.009920      -0.003492   
2 2019-12-27   0.002635            -0.005313    0.019295       0.015170   
3 2019-12-26  -0.013767            -0.010311   -0.003789       0.012275   
4 2019-12-24  -0.009982             0.003930   -0.000739      -0.004941   

   Reliance  Avenue Supermarts  Housing Development Finance Corporation  \
0 -0.019492          -0.023818                                -0.009867   
1  0.001329          -0.021360                                -0.002864   
2  0.017283           0.002057                                 0.012509   
3 -0.019406           0.007265                                 0.001286   
4 -0.015945          -0.008065                                -0.004603   

    Infosys  Asian Paints      ...        Bandhan Bank  Bharti Airtel  \
0 -0.001433     -0.008627      ...            0.007536      -0.010206   
1 -0.005429     -0.005819      ...           -0.005424       0.011421   
2  0.010353      0.001574      ...            0.012178       0.018227   
3 -0.005455      0.003715      ...            0.005520      -0.022302   
4 -0.003533     -0.002241      ...           -0.011313       0.005939   

      Titan  Tech Mahindra  Larsen Toubro  Ultratech Cement  \
0 -0.005693      -0.025120      -0.002343         -0.001357   
1  0.002728       0.002178       0.001808         -0.001085   
2 -0.001174       0.012649       0.015947         -0.001071   
3 -0.009510      -0.002330      -0.017209         -0.008908   
4 -0.003641      -0.004189      -0.007321          0.003428   

   Divis Laboratories  Pidilite Industries  Astral Polytech  Eicher Motors  
0           -0.001352            -0.014004         0.006675      -0.011330  
1            0.010937             0.006223         0.007544       0.023918  
2            0.005250             0.006334         0.008083       0.008391  
3            0.000770             0.009263         0.009565       0.007718  
4            0.006033            -0.000617         0.002551      -0.012958  

[5 rows x 25 columns]

In [107]:
returns = stocks.iloc[:,1:]
returns.head()

HDFC Bank  Kotak Mahindra Bank  ICICI Bank  Bajaj Finance  Reliance  \
0  -0.007066            -0.002192   -0.009560      -0.000649 -0.019492   
1   0.004667             0.001869   -0.009920      -0.003492  0.001329   
2   0.002635            -0.005313    0.019295       0.015170  0.017283   
3  -0.013767            -0.010311   -0.003789       0.012275 -0.019406   
4  -0.009982             0.003930   -0.000739      -0.004941 -0.015945   

   Avenue Supermarts  Housing Development Finance Corporation   Infosys  \
0          -0.023818                                -0.009867 -0.001433   
1          -0.021360                                -0.002864 -0.005429   
2           0.002057                                 0.012509  0.010353   
3           0.007265                                 0.001286 -0.005455   
4          -0.008065                                -0.004603 -0.003533   

   Asian Paints  Bajaj Finserv      ...        Bandhan Bank  Bharti Airtel  \
0     -0.008627      -0.004754      ...            0.007536      -0.010206   
1     -0.005819      -0.001366      ...           -0.005424       0.011421   
2      0.001574       0.010137      ...            0.012178       0.018227   
3      0.003715       0.005851      ...            0.005520      -0.022302   
4     -0.002241       0.000091      ...           -0.011313       0.005939   

      Titan  Tech Mahindra  Larsen Toubro  Ultratech Cement  \
0 -0.005693      -0.025120      -0.002343         -0.001357   
1  0.002728       0.002178       0.001808         -0.001085   
2 -0.001174       0.012649       0.015947         -0.001071   
3 -0.009510      -0.002330      -0.017209         -0.008908   
4 -0.003641      -0.004189      -0.007321          0.003428   

   Divis Laboratories  Pidilite Industries  Astral Polytech  Eicher Motors  
0           -0.001352            -0.014004         0.006675      -0.011330  
1            0.010937             0.006223         0.007544       0.023918  
2            0.005250             0.006334         0.008083       0.008391  
3            0.000770             0.009263         0.009565       0.007718  
4            0.006033            -0.000617         0.002551      -0.012958  

[5 rows x 24 columns]

In [108]:
ave_return = returns.mean()
ave_return

HDFC Bank                                 -0.000792
Kotak Mahindra Bank                        0.000738
ICICI Bank                                 0.001999
Bajaj Finance                              0.001911
Reliance                                   0.001362
Avenue Supermarts                          0.000799
Housing Development Finance Corporation    0.000759
Infosys                                   -0.000939
Asian Paints                               0.001054
Bajaj Finserv                              0.001494
TCS                                        0.000538
Nestle India                               0.001231
HUL                                        0.000515
Maruti Suzuki                             -0.000309
Bandhan Bank                               0.000368
Bharti Airtel                              0.000766
Titan                                      0.000991
Tech Mahindra                              0.000538
Larsen Toubro                              0.000174
Ultratech Ce

In [109]:
var_covar = returns.cov()
var_covar
n = len(returns.columns)

In [110]:
from quadprog import solve_qp

In [123]:
#Making the function
cons1 = np.matrix([np.ones(n) ,ave_return])
cons2 = np.eye(n)
C = np.concatenate([cons1,cons2],axis =0)
C = C.T
C.shape

(24, 26)

In [112]:
req_return = float(input("What is the daily rate of return required?"))

What is the daily rate of return required?0.0003


In [113]:
req_return

0.0003

In [116]:
b1 = np.array([1,req_return])
b2 = [0]*n
b= np.concatenate([b1,b2],axis=0)
b

array([1.e+00, 3.e-04, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00,
       0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00,
       0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00,
       0.e+00, 0.e+00])

In [124]:
#Model Solving
model = solve_qp(a=np.zeros(n),G=var_covar.values,C=C,b=b,meq=2)

In [125]:
model

(array([ 4.23715233e-02,  8.92662182e-02,  1.35075971e-17,  7.34437417e-18,
         5.37208001e-19,  3.55055205e-18,  1.02089512e-02,  6.52392698e-02,
        -4.95196796e-18,  9.39175209e-18,  2.18876292e-01,  0.00000000e+00,
         1.82555007e-01,  4.55844709e-02,  2.29959358e-18,  1.15109766e-02,
         1.32285788e-02,  1.06912425e-01,  1.42441555e-01,  1.02676426e-02,
        -4.38737628e-18, -8.69975486e-18,  3.73395290e-02,  2.41975608e-02]),
 3.64163253437568e-05,
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.]),
 array([13,  0]),
 array([7.93774839e-05, 2.18161106e-02, 0.00000000e+00, 0.00000000e+00,
        2.89482302e-05, 4.67876523e-05, 4.58389246e-06, 1.03638030e-05,
        0.00000000e+00, 0.00000000e+00, 5.12711138e-06, 3.04379488e-05,
        0.00000000e+00, 1.74568758e-06, 0.00000000e+00, 0.00000000e+00,
        1.05897986e-05, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.0

0.9999999999999997

In [120]:
[0]*20

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]